PaloAltoNetworks/prisma.pan.dev

docusaurus.config.js
=> updated edit URL

docs/cloud/rql/aws/aws_elb.md, docs/cloud/rql/aws/aws_s3.md, docs/cloud/rql/azure/coming_soon_azure.md, docs/cloud/rql/gcp/coming_soon_gcp.md, sidebars.js
=> Adding new s3/elb files, fixed sidebar, and modified azure/gcp top level files

docs/cloud/rql/aws/aws_ec2.md
Corrected spelling of EC2 service
=> Correct Spelling of EC2 Service

docs/cloud/rql/aws/aws_elb.md, docs/cloud/rql/aws/aws_s3.md
Fixed titles for s3 and elb files.
=> Fixed title for ELB and S3

docs/cloud/rql/gcp/gcp_cloudstorage.md, sidebars.js
Added Sidebar item for GCP Cloud Storage
Added relevant data to the page
=> RQL GCP Cloud Storage sidebar page and RQL

docs/cloud/rql/gcp/gcp_gke.md, sidebars.js
Add GCP GKE sidebar item by updating sidebars.js. Add GCP GKE RQL docs.
Create further content for users. 
Docs updated.
=> Add GCP GKE sidebar item by updating sidebars.js. Add GCP GKE RQL docs.

docs/cloud/rql/aws/aws_guardduty.md, sidebars.js, src/components/docsHome.js
Changed docsHome.js to change text to RQL Library.  Also added new aws guardduty section to library.
Change helps move us closer to full use by customers and CSs/SEs
=> Updated docsHome.js to change to RQL Library.  Added aws guardduty file.

docs/cloud/rql/azure/azure_virtual_machine.md, sidebars.js
Updating sidebars.js and added new RQL to Azure virtual machine
=> Updating sidebars.js and added new RQL to Azure virtual machine

docs/cloud/rql/azure/azure_event.md, sidebars.js
Added event RQL and sidebar.js
=> Added event RQL and sidebar.js

docs/cloud/rql/azure/coming_soon_azure.md
Remove unneeded "Azure Coming Soon" doc
Keeping the tree clean.
n/a
Tree updates
=> Remove "Azure Coming Soon" doc

src/pages/index.js
Updated title to reflect Prisma instead of PANOS.
This was confusing for people that saw the title not matching.
=> Updated title to reflect Prisma instead of PANOS.

README.md
Link pointed to panos site and header also referred to PANOS
=> Fix link to Prisma Cloud site

docs/cloud/rql/azure/azure_alb.md, docs/cloud/rql/azure/azure_app_svc.md, docs/cloud/rql/azure/azure_cosmos_db.md, docs/cloud/rql/azure/azure_sql_db.md, docs/cloud/rql/azure/azure_sql_server.md, docs/cloud/rql/azure/azure_storage.md, docs/cloud/rql/azure/azure_virtual_machine.md
modified queries with "NOTE" into "remarks" for different visibility
=> modified queries with "NOTE" into "remarks" for different visibility

docusaurus.config.js
=> fixed product menu

.gitlab-ci.yml, docusaurus.config.js
Testing internal to public publishing pipeline
This is a critical piece of our publishing pipeline.
Internal GitLab Pages, local dev server and Netlify
=> Merge internal site with public

docs/cloud/rql/gcp/gcp_compute.md
Add GCP Compute query to determine if OS-Login is enabled.
Add additional queries.
Tested on test tenant with relevant resources designated with this parameter.
-Doc update
- [X ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [ X] I have added tests to cover my changes if appropriate.
- [ X] All new and existing tests passed.
=> Add OS-Login query

docusaurus.config.js
Switch to predefined envar for URL instead of SITE_URL
=> Use predefined variable for URL instead of SITE_URL

docs/cloud_compute/policy_samples.mdx
added JSON notes stating why JSON left empty for a couple of policies.
Added one more policy with capabilities detection
=> Update Compute policies

docs/cloud/rql/iam/iam_aws.md, docs/cloud/rql/iam/iam_gen.md, sidebars.js
Added new IAM queries examples from Stuart W. @stu100wyatt
(added sidebars, new files and ref).
=> initial iam queries

docs/cloud/tf/example1.md, docs/cloud/tf/provider_doc.md, sidebars.js, src/components/docsHome.js, src/pages/index.js
Added a couple of example to use our Prisma Cloud Terraform Provider.
Sidebar, docsHome and index files were modified to add relation and links to the new TF docs.
Then new files to support it.
Let me know what you think on the consumption of it. It really is best to use complex examples in GitHub (many files), which is why I've referred to there where needed and kept the examples in the dev website to simple files for now.
If we have a way to host the files in the dev site to look like a repo in the future - even better.
I've used yarn to verify all modified pages and new entries (sidebars) to verify all is working in good order
- Breaking change (fix or feature that would …
=> Initial tf provider examples commit

docs/cloud_compute/custom_compliance_samples.md, sidebars.js, src/components/docsHome.js
Added custom compliance checks, so crowd-sourcing can add more examples. 
I used the basic examples we already use with most demos.
=> add-custom-compliance-checks-examples

docs/cloud/cspm/rql/aws/aws_cognito.md, src/components/Redocusaurus.jsx, static/oas/cspm/dist/AccessKeys.json, static/oas/cspm/dist/AccountGroups.json, static/oas/cspm/dist/AlertRules.json, static/oas/cspm/dist/Alerts.json, static/oas/cspm/dist/AnomalySettings.json, static/oas/cspm/dist/AnomalyTrustedList.json, static/oas/cspm/dist/AssetInventory.json, static/oas/cspm/dist/AuditLogs.json, static/oas/cspm/dist/CloudAccounts.json, static/oas/cspm/dist/ComplianceStandards.json, static/oas/cspm/dist/DataSecurityDashboard.json, static/oas/cspm/dist/DataSecurityInventory.json, static/oas/cspm/dist/DataSecuritySettings.json, static/oas/cspm/dist/IPAllowList.json, static/oas/cspm/dist/Integrations.json, static/oas/cspm/dist/LicensingV2.json, static/oas/cspm/dist/Login.json, static/oas/cspm/dist/NotificationTemplates.json, static/oas/cspm/dist/Policy.json, static/oas/cspm/dist/Reports.json, static/oas/cspm/dist/ResourceExplorer.json, static/oas/cspm/dist/ResourceLists.json, static/oas/cspm/dist/Search.json, static/oas/cspm/dist/SearchManager.json, static/oas/cspm/dist/Settings.json, static/oas/cspm/dist/System.json, static/oas/cspm/dist/UserProfile.json, static/oas/cspm/dist/UserRoles.json
=> redoc response buttons expanding

docs/cloud/cspm/cspm_postman_collection.md, docs/cloud/cwpp/cwpp_postman_collection.md, sidebars.js
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
=> Pubs mv add postman collection

docs/cloud/cspm/rql/aws/aws_ec2.md
removed extra cell at bottom of page
=> update to remove extra cell

api/cloud/api-integration-config.md, static/oas/cspm/CloudAccounts.yaml, static/oas/cspm/Search.yaml, static/oas/cspm/dist/CloudAccounts.json, static/oas/cspm/dist/Search.json
- Fixed some typos in api-integration-config.md
- Minor updates to possible enums in CloudAccount.yaml, Search.yaml, CloudAccount.json, Search.json
- I used vscode prettier on the JSON files
These are minor fixes but necessary to keep the API docs accurate.
Ran locally with yarn
- Bug fix
=> Minor cspm api doc updates

api/cloud/api-errors.md, api/cloud/api-headers.md, api/cloud/api-integration-config.md, api/cloud/api-time-range-model.md, api/cloud/apiurls.md, api/cloud/cspm/cspm-api.md, api/cloud/welcome-prisma-cloud-apis.md, static/oas/cspm/sidebar.js
- Added a new "home" page for CSPM API reference. Restored an existing link and moved it to this page
- Updated CSPM sidebar.js to include the new home page
- Updated sidebar labels in some of the existing md files to fit in better with the CSPM/CWPP model
- Moved the little trademark TM to conform with doc standards
- restore a sentence and link
- fits in better now that both CSPM and CWPP API docs exist
locally with yarn
- Bug fix
=> Change some text to match updated API site

docs/cloud/cspm/rql/aws/aws_ec2.md
Added an RQL query to search for a specific AMI image
Added an RQL query to search for a specific AMI image
Tested in "Investigate" tab
- Updated doc
=> Added golden AMI search query

static/oas/cwpp/Images.json
=> cwpp-api-cleanupo

src/components/Tools/index.js
Update checkov's link. The current one is broken
- [ V ] I have updated the documentation accordingly.
- [ V  ] I have read the **CONTRIBUTING** document.
- [ V  ] I have added tests to cover my changes if appropriate.
- [ V  ] All new and existing tests passed.
=> Update checkov's link

api/cloud/cspm/cspm-api.md, static/oas/cspm/AccessKeys.yaml, static/oas/cspm/CloudAccounts.yaml, static/oas/cspm/DataSecuritySettings.yaml, static/oas/cspm/Policy.yaml, static/oas/cspm/dist/AccessKeys.json, static/oas/cspm/dist/CloudAccounts.json, static/oas/cspm/dist/DataSecuritySettings.json, static/oas/cspm/dist/Policy.json
Updates for Prisma Cloud PCS 21.6.1. Descriptions will be in Prisma Cloud 21.6.1 release notes.
Required to stay in sync with regular product update. Also, minor text fixes.
Tested locally
=> 21.6.1 updates

docs/cloud/cspm/rql/azure/azure_virtual_machine.md
- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.
=> adding in new NIC example

api/cloud/cwpp/cwpp-home.md
The Enterprise and SaaS edition are the same; the method accessing it is different.
=> Added clarification on  the APIs

docs/cloud/cwpp/access-api-self-hosted.md
Linked the instructions for how to set up custom certs https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-04/prisma-cloud-compute-edition-admin/authentication/use_custom_certs_for_auth.html
=> added inline link

docs/cloud/cwpp/access-api-saas.md
Describe how to renew Compute API token for SaaS.
Our docs don't provide any info on this topic. Customer opened a case because it was not clear.
Validated with engr.
-
=> Describe how to renew Compute token.

static/oas/cspm/CloudAccounts.yaml, static/oas/cspm/DataSecuritySettings.yaml, static/oas/cspm/dist/CloudAccounts.json, static/oas/cspm/dist/DataSecuritySettings.json
- FIx path for GET /dlp/api/v1/object-inventory/resources
- Minor text update
URL path needs to be corrected
Tested locally. Also checked OpenAPI syntax with linter.
- [x ] All new and existing tests passed.
=> path fix and text fix

api/cloud/cwpp/21-04/cwpp-home.md, api/cloud/cwpp/cwpp-home.md
=> fix porting guide links

.gitlab-ci.yml
=> upgrade node

api/cloud/basic-request.md
Minor doc update to CSPM Request Basics page.
Minor fix for clarity, accuracy within the context of REST, and flow.
Run locally.
=> minor doc update

src/theme/APIDocItem/index.js
=> add issue button

src/css/custom.css
=> fix red on black

src/css/custom.css
=> Fix red code color

api/cloud/api-integration-config.md, api/cloud/basic-request.md, static/oas/cspm/AlertRules.yaml, static/oas/cspm/NotificationTemplates.yaml, static/oas/cspm/dist/AlertRules.json, static/oas/cspm/dist/NotificationTemplates.json
Minor text updates after 22.1.2 changes.
Adds clarity, including some missing details.
Tested locally
=> Minor text updates

docs/cloud/tutorials/api-basics.md, docs/cloud/tutorials/comingsoon.md, sidebars.js
=> Add new tutorial doc

src/components/Featured/index.js, src/theme/DocItemFooter/index.js, src/theme/DocItemFooter/styles.module.css
=> add code to home page and fix footer

static/oas/cspm/UserRoles.yaml, static/oas/cspm/dist/UserRoles.json
=> Add 'list user role type' API for CSPM 22.4.2

docs/cloud/cspm/rql/aws/aws_ec2.md
Search for an EC2 instance from a public IP address.
My code add a new RQL example in documentation.
=> Add a new RQL example for EC2 instances

api/cloud/api-integration-config.md, static/oas/cspm/AuditLogs.yaml, static/oas/cspm/dist/AuditLogs.json
=> CSPM 22.5.1 API updates

docs/cloud/cspm/rql/gcp/gcp_project.md, sidebars.js
=> feat: add new page for GCP Project RQL example

static/oas/cspm/Alerts.yaml, static/oas/cspm/dist/Alerts.json
=> CSPM 22.5.2 updates

docs/cloud/cwpp/access-api-self-hosted.md
This adds a comment regarding requests with "Projects" enabled. I happened to find this information here: https://docs.paloaltonetworks.com/prisma/prisma-cloud/21-08/prisma-cloud-compute-edition-admin/deployment_patterns/projects
The particular phrasing/terms are likely incorrect.
We were unable to perform any API requests with a non-admin user. All requests returned Forbidden response.
=> Add note regarding API requests in multi-tenant environment

src/css/custom.css
=> make collapse bigger

static/oas/cwpp/Audits.json, static/oas/cwpp/Authenticate-Client.json, static/oas/cwpp/Authenticate.json, static/oas/cwpp/Cloud.json, static/oas/cwpp/Collections.json, static/oas/cwpp/Containers.json, static/oas/cwpp/Credentials.json, static/oas/cwpp/Current.json, static/oas/cwpp/Custom-Compliance.json, static/oas/cwpp/Custom-Rules.json, static/oas/cwpp/Defenders.json, static/oas/cwpp/Groups.json, static/oas/cwpp/Hosts.json, static/oas/cwpp/Images.json, static/oas/cwpp/Policies.json, static/oas/cwpp/Profiles.json, static/oas/cwpp/Registry.json, static/oas/cwpp/Scans.json, static/oas/cwpp/Serverless.json, static/oas/cwpp/Settings.json, static/oas/cwpp/Signup.json, static/oas/cwpp/Stats.json, static/oas/cwpp/Statuses.json, static/oas/cwpp/Tags.json, static/oas/cwpp/Users.json, static/oas/cwpp/Util.json, static/oas/cwpp/Version.json, static/oas/cwpp/Waas.json
Build number was wrong and so reverted to the build 197 for Kepler Update 1.
Fixes an issue for the wrong build number.
Tested on a local yarn site.
=> Rebuild Site for Kepler Update 1 (Build 197)

static/oas/cwpp/Audits.json, static/oas/cwpp/Authenticate-Client.json, static/oas/cwpp/Authenticate.json, static/oas/cwpp/Cloud.json, static/oas/cwpp/Collections.json, static/oas/cwpp/Containers.json, static/oas/cwpp/Credentials.json, static/oas/cwpp/Current.json, static/oas/cwpp/Custom-Compliance.json, static/oas/cwpp/Custom-Rules.json, static/oas/cwpp/Defenders.json, static/oas/cwpp/Groups.json, static/oas/cwpp/Hosts.json, static/oas/cwpp/Images.json, static/oas/cwpp/Policies.json, static/oas/cwpp/Profiles.json, static/oas/cwpp/Registry.json, static/oas/cwpp/Scans.json, static/oas/cwpp/Serverless.json, static/oas/cwpp/Settings.json, static/oas/cwpp/Signup.json, static/oas/cwpp/Stats.json, static/oas/cwpp/Statuses.json, static/oas/cwpp/Tags.json, static/oas/cwpp/Users.json, static/oas/cwpp/Util.json, static/oas/cwpp/Version.json, static/oas/cwpp/Waas.json
Updated microspecs for Kepler Update 2.
Maintenance release update.
Tested on a local.
GH #39754 - New API for Fargate task in YAML
=> [Compute API] Updated microspecs for Kepler Update 2

api/cloud/cspm/permissiongroups.mdx, static/oas/cspm/PermissionGroups.yaml, static/oas/cspm/UserProfile.yaml, static/oas/cspm/UserRoles.yaml, static/oas/cspm/dist/PermissionGroups.json, static/oas/cspm/dist/UserProfile.json, static/oas/cspm/dist/UserRoles.json
API reference changes for several endpoints. Added a new category: Permission Groups. Modified a few existing endpoint descriptions within UserRoles and UserProfile categories.
https://redlock.atlassian.net/browse/RLP-50997
=> [Preview: DO NOT MERGE YET] added a Permission Groups category. Modified UserProfile and UserRoles

api/cloud/apiurls.md, static/oas/cspm/ArchivedAssets.yaml, static/oas/cspm/dist/ArchivedAssets.json
Added response samples for the Archived Assets API.
Provides information about handling errors to customers.
Tested locally using yarn start. 
=> Update Archived Assets API and URLs list

static/oas/cspm/dist/Alerts.json, static/oas/cspm/dist/AssetExplorer.json
Content changes for Alerts and AssetExplorer
=> Release 12.1

static/oas/cspm/ArchivedAssets.yaml, static/oas/cspm/dist/ArchivedAssets.json
Update Archived Assets API
Update descriptions for attributes
Tested locally using yarn start 
=> Update Archived Assets API

api/cloud/cwpp/api-limits.md, docs/cloud/cwpp/access-api-saas.md, docs/cloud/cwpp/access-api-self-hosted.md, static/oas/cwpp/22-01/Custom-Rules.json, static/oas/cwpp/22-01/Util.json, static/oas/cwpp/22-06/Custom-Rules.json, static/oas/cwpp/22-06/Util.json, static/oas/cwpp/Custom-Rules.json, static/oas/cwpp/Util.json, static/oas/cwpp/Vms.json
Added update for GH#37375 for Lagrange and other updated microspecs.
Feature addition and other corrections.
Tested in a local environment.
- Bug fix (non-breaking change)
=> Gh37375 page size limit

static/oas/cspm/dist/AdoptionAdvisor.json, static/oas/cspm/dist/Alerts.json, static/oas/cspm/dist/AssetExplorer.json, static/oas/cspm/dist/AssetInventory.json, static/oas/cspm/dist/IPAllowList.json
23.1.1 release
Addresses changes for:
Assert Explorer and Asset Inventory:
https://redlock.atlassian.net/browse/RLP-86136
https://redlock.atlassian.net/browse/RLP-86061
https://redlock.atlassian.net/browse/RLP-85703
Adoption Advisor
https://redlock.atlassian.net/browse/RLP-84623
=> Cspm release 23.1.1

static/oas/cspm/AdoptionAdvisor.yaml, static/oas/cspm/dist/AdoptionAdvisor.json, static/oas/cspm/dist/AssetInventory.json, static/oas/cspm/dist/CompliancePosture.json
added Adoption Advisor endpoints (6); added response properties in Asset Inventory and Compliance Posture
23.1.2 Release preview
=> CSPM 23.1.2 Release Preview

docusaurus.config.js, src/theme/AnnouncementBar/index.js, src/theme/AnnouncementBar/styles.module.css, yarn.lock
=> add banner

docusaurus.config.js, firebase.json, src/theme/AnnouncementBar/index.js, src/theme/NotFound.js
=> more redirects, redirect 404s to pan.dev, update banner
